### PR TITLE
Changed the whole main page

### PR DESCRIPTION
**Pull request by Abhilash107**

### CODE REVIEW

**Comment by PandaAnshuman** [comment]
@Abhilash107  Add some proof like videos or screenshot on the changes you have done

**Comment by Abhilash107** [comment]
https://github.com/CareerDevelopmentHub/receipe_finder/assets/130066893/0b959b80-d76d-440f-ac40-a843b29c2216

**Comment by PandaAnshuman** [comment]
@Abhilash107  Your PR is having Merge Conflicts so I'm not able to merge it

**Comment by Abhilash107** [comment]
Sir can i pull req again?

**Pull request closed without merging**
